spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml
  application:
    name: liquibase demo

  datasource:
    url: jdbc:mysql://${DB_HOST}}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        generate_statistics: true
        order_inserts: true
        order_updates: true


server:
  jetty:
    threads:
      idle-timeout: 2000ms