
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  application:
    name: liquibase demo

  datasource:
    url: jdbc:mysql://mysqldb:3306/aircondition
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gomaa
    password: 1234567

#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 10
#          generate_statistics: true
#          order_inserts: true


  h2:
    console:
      enabled: none



server:
  jetty:
    threads:
      idle-timeout: 2000ms