spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml
  application:
    name: liquibase demo

  datasource:
    url: jdbc:mysql://mysqldb:3306/aircondition
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gomaa
    password: 1234567

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        generate_statistics: true
        order_inserts: true
        order_updates: true


server:
  jetty:
    threads:
      idle-timeout: 2000ms