
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  application:
    name: liquibase demo

  datasource:
    url: jdbc:mysql://localhost:3306/aircondition
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


  h2:
    console:
      enabled: none



server:
  jetty:
    threads:
      idle-timeout: 2000ms