apiVersion: apps/v1
kind: Deployment
metadata:
  name: aircondition-deployment
spec:
  selector:
    matchLabels:
      app: aircondition
  replicas: 3
  template:
    metadata:
      labels:
        app: aircondition
    spec:
      containers:
        - name: aircondition-app
          image: gomaa123/aircondition:V151
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST # Setting Database host address from configMap
              value: mysql

            - name: DB_NAME # Setting Database name from configMap
              value: aircondition

            - name: DB_USER # Setting Database username from Secret
              value: gomaa

            - name: DB_PASSWORD # Setting Database password from Secret
              value: gomaa
---


apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: aircondition-svc
spec:
  selector:
    app: aircondition
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
